// <auto-generated />
using System;
using App.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    [Migration("20260720105532_make_lot_location_nullable")]
    partial class make_lot_location_nullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("App.Models.Bet", b =>
                {
                    b.Property<uint>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("lot_id")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("price")
                        .HasColumnType("TEXT");

                    b.Property<string>("user_login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("lot_id");

                    b.HasIndex("user_login");

                    b.ToTable("bets");
                });

            modelBuilder.Entity("App.Models.Lot", b =>
                {
                    b.Property<uint>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("count")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("current_price")
                        .HasColumnType("TEXT");

                    b.Property<string>("delivery_payment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("end_time")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("initial_price")
                        .HasColumnType("TEXT");

                    b.Property<string>("location")
                        .HasColumnType("TEXT");

                    b.Property<string>("payment_method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("tag_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("user_login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("tag_id");

                    b.HasIndex("user_login");

                    b.ToTable("lots");
                });

            modelBuilder.Entity("App.Models.LotImage", b =>
                {
                    b.Property<uint>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("image_path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("lot_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("lot_id");

                    b.ToTable("lot_images");
                });

            modelBuilder.Entity("App.Models.Tag", b =>
                {
                    b.Property<uint>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("tags");
                });

            modelBuilder.Entity("App.Models.User", b =>
                {
                    b.Property<string>("login")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("login");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("App.Models.Bet", b =>
                {
                    b.HasOne("App.Models.Lot", "lot")
                        .WithMany()
                        .HasForeignKey("lot_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Models.User", "user")
                        .WithMany("bets")
                        .HasForeignKey("user_login")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("lot");

                    b.Navigation("user");
                });

            modelBuilder.Entity("App.Models.Lot", b =>
                {
                    b.HasOne("App.Models.Tag", "tag")
                        .WithMany("lots")
                        .HasForeignKey("tag_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Models.User", "user")
                        .WithMany("lots")
                        .HasForeignKey("user_login")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tag");

                    b.Navigation("user");
                });

            modelBuilder.Entity("App.Models.LotImage", b =>
                {
                    b.HasOne("App.Models.Lot", "lot")
                        .WithMany("images")
                        .HasForeignKey("lot_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("lot");
                });

            modelBuilder.Entity("App.Models.Lot", b =>
                {
                    b.Navigation("images");
                });

            modelBuilder.Entity("App.Models.Tag", b =>
                {
                    b.Navigation("lots");
                });

            modelBuilder.Entity("App.Models.User", b =>
                {
                    b.Navigation("bets");

                    b.Navigation("lots");
                });
#pragma warning restore 612, 618
        }
    }
}
