// <auto-generated />
using System;
using App.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    [Migration("20260720101248_add_bets_and_update_lots")]
    partial class add_bets_and_update_lots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("App.Models.Bet", b =>
                {
                    b.Property<uint>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("lot_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("user_login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("bets");
                });

            modelBuilder.Entity("App.Models.Lot", b =>
                {
                    b.Property<uint>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("count")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("current_price")
                        .HasColumnType("TEXT");

                    b.Property<string>("delivery_payment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("end_time")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("initial_price")
                        .HasColumnType("TEXT");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("payment_method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("tag_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("user_login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("lots");
                });

            modelBuilder.Entity("App.Models.LotImage", b =>
                {
                    b.Property<uint>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("image_path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("lot_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("lot_images");
                });

            modelBuilder.Entity("App.Models.Tag", b =>
                {
                    b.Property<uint>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("tags");
                });

            modelBuilder.Entity("App.Models.User", b =>
                {
                    b.Property<string>("login")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("login");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
