// <auto-generated />
using System;
using App.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace App.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    partial class AuctionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("App.Models.Bid", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long>("lot_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("price")
                        .HasColumnType("numeric");

                    b.Property<string>("user_login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("lot_id");

                    b.HasIndex("user_login");

                    b.ToTable("bids");
                });

            modelBuilder.Entity("App.Models.Lot", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("city")
                        .HasColumnType("text");

                    b.Property<bool>("closed")
                        .HasColumnType("boolean");

                    b.Property<int>("count")
                        .HasColumnType("integer");

                    b.Property<decimal>("current_price")
                        .HasColumnType("numeric");

                    b.Property<string>("delivery_payment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("end_time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("initial_price")
                        .HasColumnType("numeric");

                    b.Property<string>("leader_login")
                        .HasColumnType("text");

                    b.Property<string>("payment_method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("tag_id")
                        .HasColumnType("bigint");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("user_login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("leader_login");

                    b.HasIndex("tag_id");

                    b.HasIndex("user_login");

                    b.ToTable("lots");
                });

            modelBuilder.Entity("App.Models.LotImage", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("image_path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("lot_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("lot_id");

                    b.ToTable("lot_images");
                });

            modelBuilder.Entity("App.Models.Purchase", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<decimal>("locked_price")
                        .HasColumnType("numeric");

                    b.Property<long>("lot_id")
                        .HasColumnType("bigint");

                    b.Property<string>("user_login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("lot_id");

                    b.HasIndex("user_login");

                    b.ToTable("purchases");
                });

            modelBuilder.Entity("App.Models.Tag", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("tags");
                });

            modelBuilder.Entity("App.Models.User", b =>
                {
                    b.Property<string>("login")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<bool>("is_admin")
                        .HasColumnType("boolean");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("login");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("App.Models.Bid", b =>
                {
                    b.HasOne("App.Models.Lot", "lot")
                        .WithMany("bids")
                        .HasForeignKey("lot_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Models.User", "user")
                        .WithMany("bets")
                        .HasForeignKey("user_login")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("lot");

                    b.Navigation("user");
                });

            modelBuilder.Entity("App.Models.Lot", b =>
                {
                    b.HasOne("App.Models.User", "leader")
                        .WithMany()
                        .HasForeignKey("leader_login");

                    b.HasOne("App.Models.Tag", "tag")
                        .WithMany("lots")
                        .HasForeignKey("tag_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Models.User", "user")
                        .WithMany("lots")
                        .HasForeignKey("user_login")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("leader");

                    b.Navigation("tag");

                    b.Navigation("user");
                });

            modelBuilder.Entity("App.Models.LotImage", b =>
                {
                    b.HasOne("App.Models.Lot", "lot")
                        .WithMany("images")
                        .HasForeignKey("lot_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("lot");
                });

            modelBuilder.Entity("App.Models.Purchase", b =>
                {
                    b.HasOne("App.Models.Lot", "lot")
                        .WithMany()
                        .HasForeignKey("lot_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Models.User", "user")
                        .WithMany("purchases")
                        .HasForeignKey("user_login")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("lot");

                    b.Navigation("user");
                });

            modelBuilder.Entity("App.Models.Lot", b =>
                {
                    b.Navigation("bids");

                    b.Navigation("images");
                });

            modelBuilder.Entity("App.Models.Tag", b =>
                {
                    b.Navigation("lots");
                });

            modelBuilder.Entity("App.Models.User", b =>
                {
                    b.Navigation("bets");

                    b.Navigation("lots");

                    b.Navigation("purchases");
                });
#pragma warning restore 612, 618
        }
    }
}
